name: Build

on:
  push:
    branches:
      - main
      - rust-server
  workflow_dispatch:

jobs:
  build-site:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - name: Build site
        run: |
          npm ci
          npm run build
      - name: Archive site
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: dist

  build-server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-server-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.66.0
          override: true
      - name: Build site
        run: cargo build --release
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: ofcrse
          path: target/release/ofcrse
